stages:
  - test
  - report
  - report-upload

cache:
  key: composer-cache
  paths:
    - .composer-cache/

.test:
  before_script:
    # display PHP version
    - php -v
    # install system packages
    - apt-get update && apt-get install -y git unzip libgmp-dev
    # install extensions
    - docker-php-ext-install gmp bcmath
    - if [ "$INSTALL_XDEBUG" -eq 1 ]; then pecl install xdebug; docker-php-ext-enable xdebug; fi
    # install composer
    - php -r "copy('https://composer.github.io/installer.sig', '/tmp/composer.sig');"
    - php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    - php -r '$expected = file_get_contents("/tmp/composer.sig"); $actual = hash_file("sha384", "/tmp/composer-setup.php"); exit(intval(!hash_equals($expected, $actual)));'
    - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - chmod +x /usr/local/bin/composer
    - rm /tmp/composer-setup.php /tmp/composer.sig
    # cache dependencies
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  script:
    - composer update
    - vendor/bin/phpunit --fail-on-deprecation --fail-on-notice --fail-on-warning

# coverage
coverage:
  variables:
    INSTALL_XDEBUG: 1
  extends: .test
  stage: report
  only:
    - master
  image: php:8.4
  artifacts:
    paths:
      - reports
    expire_in: 1h
  script:
    - composer update
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-clover reports/coverage.xml --log-junit reports/junit.xml

coverage-upload:
  stage: report-upload
  image: python:3.12
  only:
    - master
  before_script:
    - pip install codecov-cli
  script:
    - codecovcli do-upload --report-type test_results --file reports/junit.xml --token $CODECOV_TOKEN
    - codecovcli upload-process --file reports/coverage.xml --token $CODECOV_TOKEN

# lowest version
test-8.1:
  extends: .test
  stage: test
  image: php:8.1

# lowest bcmath
test-8.4:
  extends: .test
  stage: test
  image: php:8.4

# latest PHP 8
test-8:
  extends: .test
  stage: test
  image: php:8
