stages:
  - test

cache:
  key: composer-cache
  paths:
    - .composer-cache/

.test:
  before_script:
    # install system packages
    - apt-get update && apt-get install -y git unzip libgmp-dev
    # install extensions
    - docker-php-ext-install gmp
    - if [ "$INSTALL_XDEBUG" -eq 1 ]; then curl --location https://github.com/FriendsOfPHP/pickle/releases/latest/download/pickle.phar --output pickle.phar; php pickle.phar install xdebug; docker-php-ext-enable xdebug; fi
    # install composer
    - php -r "copy('https://composer.github.io/installer.sig', '/tmp/composer.sig');"
    - php -r "copy('https://getcomposer.org/installer', '/tmp/composer-setup.php');"
    - php -r '$expected = file_get_contents("/tmp/composer.sig"); $actual = hash_file("sha384", "/tmp/composer-setup.php"); exit(intval(!hash_equals($expected, $actual)));'
    - php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
    - chmod +x /usr/local/bin/composer
    - rm /tmp/composer-setup.php /tmp/composer.sig
    # cache dependencies
    - composer config -g cache-dir "$(pwd)/.composer-cache"
  script:
    - composer update
    - vendor/bin/phpunit

# lowest version && coverage
test-8.0:
  variables:
    INSTALL_XDEBUG: 1
  extends: .test
  stage: test
  image: php:8.0
  script:
    - composer update
    - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-cobertura=reports/coverage.xml --coverage-filter src
  artifacts:
    reports:
      cobertura: reports/coverage.xml

# latest unstable
test-rc:
  extends: .test
  stage: test
  image: php:rc
  allow_failure: true
